import { ProductSizeSchema } from "@/schemas/Menu/ProductSchema";
import z from "zod";

// create table public.order_items (
//   id integer generated by default as identity not null,
//   created_at timestamp with time zone not null default now(),
//   product_id integer not null,
//   product_name character varying not null,
//   price_at_purchase numeric(10, 2) not null default 0.00,
//   order_id integer not null,
//   quantity smallint not null default '1'::smallint,
//   product_size public.product_size not null default 'S'::product_size,
//   constraint order_items_pkey primary key (id),
//   constraint order_items_order_id_fkey foreign KEY (order_id) references orders (id) on delete CASCADE,
//   constraint order_items_product_id_fkey foreign KEY (product_id) references products (id)
// ) TABLESPACE pg_default;

export const CreateOrderItemSchema = z.object({
  product_id: z.number().nonnegative(),
  product_name: z.string(),
  price_at_purchase: z.number().nonnegative(),
  quantity: z.number(),
  product_size: ProductSizeSchema,
});

export const CreateOrderItemsSchema = z.array(CreateOrderItemSchema);

export const OrderItemSchema = z.object({
  id: z.number(),
  created_at: z.string(),
  product_id: z.number(),
  product_name: z.string(),
  price_at_purchase: z.number().nonnegative(),
  order_id: z.number(),
  quantity: z.number().min(1),
  product_size: z.enum(["S", "M", "L"]),
});

export const OrderItemWithImageSchema = OrderItemSchema.extend({
  image_url: z.string(),
});

export const OrderItemWithImageAndCategorySchema = OrderItemSchema.extend({
  image_url: z.string(),
  category: z.enum(["hot", "cold"]),
});
