import { ProductSizeSchema } from "@/hooks/useMenuPageDetailSearchParams";
import { z } from "zod";

//   id integer generated by default as identity not null,
//   created_at timestamp with time zone not null default now(),
//   product_id integer not null,
//   product_name character varying not null,
//   price_at_purchase numeric(10, 2) not null default 0.00,
//   order_id integer not null,
//   quantity smallint not null default '1'::smallint,
//   product_size public.product_size not null default 'S'::product_size,

export const OrderItemSchema = z.object({
  id: z.number().int(),
  product_id: z.number().int(),
  product_name: z.string(),
  price_at_purchase: z.number().nonnegative(),
  order_id: z.number().int(),
  quantity: z.number().int().nonnegative().min(1),
  product_size: ProductSizeSchema,
});
